---
# Source: tomcat/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: tomcat
  namespace: tomcat
  labels:
    app.kubernetes.io/name: tomcat
    helm.sh/chart: tomcat-10.3.15
    app.kubernetes.io/instance: tomcat
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  tomcat-password: "dzFkR0F4ZjNBdA=="
