---
# Source: tomcat/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: release-name-tomcat
  namespace: ingress
  labels:
    app.kubernetes.io/name: tomcat
    helm.sh/chart: tomcat-10.3.9
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  tomcat-password: "QnpSZWxWSDlETA=="
