---
# Source: tomcat/templates/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: tomcat
  namespace: tomcat
  labels:
    app.kubernetes.io/name: tomcat
    helm.sh/chart: tomcat-10.3.15
    app.kubernetes.io/instance: tomcat
    app.kubernetes.io/managed-by: Helm
spec:
  type: LoadBalancer
  externalTrafficPolicy: "Cluster"
  sessionAffinity: None
  ports:
    - name: http
      port: 80
      targetPort: http
  selector: 
    app.kubernetes.io/name: tomcat
    app.kubernetes.io/instance: tomcat
